### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by philbucher** [philbucher/KratosSalomePlugin#76]
Dear friends of Kratos,

:tada:  :tada:  :tada: I am very pleased to announce **release 1.0 of the Kratos Salome Plugin**. :tada:  :tada:  :tada: 

After working with Salome for over three years and having as many previous (non-published) versions of this Plugin, I was finally able to bring my work to a state in which it is also usable for others.

[LINK TO RELEASE](https://github.com/philbucher/KratosSalomePlugin/releases/tag/v1.0.0)

This is a first step towards a proper integation of Kratos in Salome. As this is the very first public release, some things are not yet developed, most notably the GUI and the interfaces for Kratos Applications. I started already with this, it will be part of release 2.0. A roadmap for future developments can be found [here](https://github.com/philbucher/KratosSalomePlugin/issues/64).
Please also check [this issue](https://github.com/philbucher/KratosSalomePlugin/issues/32) for the status of the current status of developments

Aside from this the plugin is fully operational and can be used for creating Kratos input (mdpa files) from Salome meshes in the TUI/batch mode (this is my usual usecase).

I already added some [examples](https://github.com/philbucher/KratosSalomePlugin/tree/master/tui_examples) (currently 2) which show common usecases that this plugin can handle.

Basic documentation is also available [here](https://github.com/philbucher/KratosSalomePlugin/tree/master/documentation).

I am using this already for some time in production, hence I am quite confident I could eliminate many bugs already. Furthermore from the beginning I heavily tested everything.

#

If you want to try this I recommend taking a look at the [README](https://github.com/philbucher/KratosSalomePlugin). There all the steps are explained. 
In case you need assistance or found a problem, please open an issue.

Since this is still a rather young implementation, *I would really appreciate if you could send me the log-files (`kratos_salome_plugin.log`) that are generated by the plugin*. This will help me a lot with the future developments.

#

I am tagging everyone that showed interest in this in the past:
@pooyan-dadvand @RiccardoRossi @rubenzorrilla @rolandwuechner @inigolcanalejo @emiroglu  @sunethwarna @MFusseder @adityaghantasala @dbaumgaertner @armingeiser @KlausBSautter @mpentek @AndreasWinterstein @e-dub @thelfer @loumalouomega @navaneethkn @marcnunezc

**Comment by pooyan-dadvand** [comment]
Any plan to move it to KratosMultiphysics like the GiD one?

**Comment by philbucher** [comment]
> Any plan to move it to KratosMultiphysics like the GiD one?

is is certainly planned, my idea is documented [here](https://github.com/philbucher/KratosSalomePlugin/issues/32)

We can discuss when to move it

**Comment by philbucher** [comment]
closing this as release 1.1 is underway, which contains the first version of the **GUI** (for mesh conversion aka mdpa writing)
